apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-operator
  namespace: redis-operator-system
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: redis-operator
