//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisAuthSpec.
func (in *RedisAuthSpec) DeepCopy() *RedisAuthSpec {
	if in == nil {
		return nil
	}
	out := new(RedisAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisInstance) DeepCopyInto(out *RedisInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisInstance.
func (in *RedisInstance) DeepCopy() *RedisInstance {
	if in == nil {
		return nil
	}
	out := new(RedisInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisInstanceList) DeepCopyInto(out *RedisInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedisInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisInstanceList.
func (in *RedisInstanceList) DeepCopy() *RedisInstanceList {
	if in == nil {
		return nil
	}
	out := new(RedisInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedisInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisInstanceSpec.
func (in *RedisInstanceSpec) DeepCopy() *RedisInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(RedisInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisInstanceStatus.
func (in *RedisInstanceStatus) DeepCopy() *RedisInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(RedisInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisStorageSpec.
func (in *RedisStorageSpec) DeepCopy() *RedisStorageSpec {
	if in == nil {
		return nil
	}
	out := new(RedisStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisTLSSpec.
func (in *RedisTLSSpec) DeepCopy() *RedisTLSSpec {
	if in == nil {
		return nil
	}
	out := new(RedisTLSSpec)
	in.DeepCopyInto(out)
	return out
}
