package controllers

import (
	"context"
	"fmt"
	"sort"
	"strings"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"

	redisv1alpha1 "github.com/example/redis-operator/api/v1alpha1"
)

func configMapName(instance *redisv1alpha1.RedisInstance) string {
	return fmt.Sprintf("%s-config", instance.Name)
}

func renderRedisConf(config map[string]string) string {
	var sb strings.Builder
	// Base settings
	sb.WriteString("# Generated by redis-operator\n")
	sb.WriteString("dir /data\n")
	sb.WriteString("protected-mode no\n")

	// Sort keys for determinism
	keys := make([]string, 0, len(config))
	for k := range config {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Fprintf(&sb, "%s %s\n", k, config[k])
	}
	return sb.String()
}

func (r *RedisInstanceReconciler) reconcileConfigMap(ctx context.Context, instance *redisv1alpha1.RedisInstance) error {
	desired := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      configMapName(instance),
			Namespace: instance.Namespace,
			Labels:    labelsForInstance(instance),
		},
		Data: map[string]string{
			"redis.conf": renderRedisConf(instance.Spec.Config),
		},
	}
	if err := ctrl.SetControllerReference(instance, desired, r.Scheme); err != nil {
		return err
	}

	existing := &corev1.ConfigMap{}
	err := r.Get(ctx, types.NamespacedName{Namespace: instance.Namespace, Name: configMapName(instance)}, existing)
	if errors.IsNotFound(err) {
		return r.Create(ctx, desired)
	}
	if err != nil {
		return err
	}

	existing.Data = desired.Data
	return r.Update(ctx, existing)
}
